language: node_js
node_js:
  - "node"
  - "lts/*"
service:
  - mongodb
script:
  - npm install codecov -g
  - npm i
  - npm run build
  - npm run coverage
  - npm run report
after_success:
  - codecov
